### ISSUE TITLE
GPU support for non-symmetric eigenvalue solver 

### ISSUE THREAD

**Issue by gautierronan** [icl-utk-edu/magma#12]
As I can see in the [MAGMA handout](https://icl.utk.edu/files/print/2023/magma-sc23.pdf), there is no GPU support yet for non-symmetric eigenvalue solvers. Would this planned in the near future? 

We'd be interested in this in the context of [dynamiqs](https://github.com/dynamiqs/dynamiqs), a JAX-based library for the simulation of quantum systems. Thanks!

**Comment by abdelfattah83** [comment]
We do have GPU support for non-symmetric eigensolvers (magma_dgeev for example for double precision). The handout mentions that there is only a "CPU interface" meaning that the matrix should be in the host memory before calling the MAGMA routine. However, GPUs are still used internally by the routine. 

We don't have a version that starts with the matrix resident in the GPU memory.

**Comment by gautierronan** [comment]
Roger that, thanks a lot for clarifying!
