### ISSUE TITLE
Missing 2.8.0 release

### ISSUE THREAD

**Issue by lahwaacz** [icl-utk-edu/magma#13]
The [2.8.0 release](https://icl.utk.edu/magma/downloads/) is missing on GitHub: https://github.com/icl-utk-edu/magma/tags

**Comment by abdelfattah83** [comment]
Thank you for reporting this. 
The 2.8.0 tag is added. Note that tags differ from the official releases posted on MAGMA's home page here (https://icl.utk.edu/magma/). A little background below:

With very few exceptions, MAGMA is primarily developed in double-complex precision, and relies on a 'precision generator' to generate the other three precisions (single, double, and single-complex). The official releases on MAGMA's homepage are tarballs that contains all the source files for all four standard precisions. If you download directly from GitHub, the MAGMA build system will run the precision generator first before compilation. Both are basically the same thing, but with an extra step if you use the tags.

**Comment by lahwaacz** [comment]
I understand the difference, we would just like to move from https://bitbucket.org/icl/magma.git to github for the source in the [Arch Linux package](https://gitlab.archlinux.org/archlinux/packaging/packages/magma). How is the migration going? I hope future tags will appear on github early :smile:

**Comment by abdelfattah83** [comment]
The migration is complete. We no longer use bitbucket, which will be deleted soon. I don't know how the 2.8.0 tag was dropped during migration, though.
