### ISSUE TITLE
Setting GPU_TARGET doesn't do anything

### ISSUE THREAD

**Issue by G-Ragghianti** [icl-utk-edu/magma#2]
Setting GPU_TARGET=Volta or GPU_TARGET=sm_70 doesn't have any effect.  Using cuobjdump, one can see that only PTX for sm_52 (Maxwell) are created.

**Comment by G-Ragghianti** [comment]
Created https://github.com/icl-utk-edu/magma/pull/3 to address this.

**Comment by FuncJ** [comment]
Can the MAGMA library be used on a server that contains only CPU processors?

> Setting GPU_TARGET=Volta or GPU_TARGET=sm_70 doesn't have any effect. Using cuobjdump, one can see that only PTX for sm_52 (Maxwell) are created.

**Comment by G-Ragghianti** [comment]
> Can the MAGMA library be used on a server that contains only CPU processors? `magmablas_xxx_batched`

I don't believe so.
